-- ============================================================
-- Fulusy Initial Schema - Oracle 21c
-- ============================================================

-- USERS -------------------------------------------------------
CREATE TABLE users (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                  VARCHAR2(255) NOT NULL UNIQUE,
    password_hash          VARCHAR2(255) NOT NULL,
    name                   VARCHAR2(100) NOT NULL,
    starting_balance       NUMBER(15, 2) DEFAULT 0 NOT NULL,
    income_mode            VARCHAR2(20)  NOT NULL
        CHECK (income_mode IN ('fixed', 'variable', 'hybrid')),
    fixed_income_amount    NUMBER(15, 2),
    fixed_income_day       NUMBER(2) CHECK (fixed_income_day BETWEEN 1 AND 31),
    currency               VARCHAR2(10)  DEFAULT 'EGP' NOT NULL,
    language               VARCHAR2(2)   DEFAULT 'ar'  NOT NULL
        CHECK (language IN ('ar', 'en')),
    visual_style           VARCHAR2(20)  DEFAULT 'minimalist' NOT NULL,
    monthly_savings_goal   NUMBER(15, 2),
    created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- USER_SETTINGS -----------------------------------------------
CREATE TABLE user_settings (
    id                         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    NUMBER NOT NULL UNIQUE,
    sound_enabled              NUMBER(1) DEFAULT 0 NOT NULL,
    haptics_enabled            NUMBER(1) DEFAULT 0 NOT NULL,
    daily_reminder_time        VARCHAR2(5),
    salary_reminder            NUMBER(1) DEFAULT 1 NOT NULL,
    budget_warnings            NUMBER(1) DEFAULT 1 NOT NULL,
    streak_milestones          NUMBER(1) DEFAULT 1 NOT NULL,
    check_in_frequency         VARCHAR2(20) DEFAULT 'bi_weekly' NOT NULL
        CHECK (check_in_frequency IN ('weekly', 'bi_weekly', 'monthly')),
    savings_goal_allocation    VARCHAR2(20) DEFAULT 'general_pool' NOT NULL,
    missed_deadline_behavior   VARCHAR2(20) DEFAULT 'mark_failed' NOT NULL,
    CONSTRAINT fk_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- BUDGETS -----------------------------------------------------
CREATE TABLE budgets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    category_id     VARCHAR2(20) NOT NULL
        CHECK (category_id IN ('essentials', 'transport', 'luxuries', 'shopping', 'other')),
    monthly_limit   NUMBER(15, 2) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_budget_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_budget_user_cat UNIQUE (user_id, category_id)
);

-- EXPENSES ----------------------------------------------------
CREATE TABLE expenses (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL,
    amount         NUMBER(15, 2) NOT NULL CHECK (amount > 0),
    category_id    VARCHAR2(20) NOT NULL
        CHECK (category_id IN ('essentials', 'transport', 'luxuries', 'shopping', 'other')),
    note           VARCHAR2(500),
    expense_date   DATE NOT NULL,
    is_recurring   NUMBER(1) DEFAULT 0 NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_expenses_user_date ON expenses(user_id, expense_date DESC);
CREATE INDEX idx_expenses_user_cat  ON expenses(user_id, category_id);

-- INCOMES -----------------------------------------------------
CREATE TABLE incomes (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    amount        NUMBER(15, 2) NOT NULL CHECK (amount > 0),
    source        VARCHAR2(30) NOT NULL
        CHECK (source IN ('salary', 'freelance', 'gift', 'gam3eya_payout', 'bonus', 'other')),
    note          VARCHAR2(500),
    income_date   DATE NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_income_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_incomes_user_date ON incomes(user_id, income_date DESC);

-- SAVINGS_CONTRIBUTIONS ---------------------------------------
CREATE TABLE savings_contributions (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             NUMBER NOT NULL,
    amount              NUMBER(15, 2) NOT NULL CHECK (amount > 0),
    source              VARCHAR2(30) NOT NULL
        CHECK (source IN ('manual', 'month_rollover', 'goal_contribution')),
    note                VARCHAR2(500),
    contribution_date   DATE NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_savings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_savings_user_date ON savings_contributions(user_id, contribution_date DESC);

-- GOALS -------------------------------------------------------
CREATE TABLE goals (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER NOT NULL,
    name              VARCHAR2(100) NOT NULL,
    icon              VARCHAR2(20),
    target_amount     NUMBER(15, 2) NOT NULL CHECK (target_amount > 0),
    starting_amount   NUMBER(15, 2) DEFAULT 0 NOT NULL,
    current_amount    NUMBER(15, 2) DEFAULT 0 NOT NULL,
    deadline          DATE NOT NULL,
    priority          VARCHAR2(10) DEFAULT 'medium' NOT NULL
        CHECK (priority IN ('low', 'medium', 'high')),
    status            VARCHAR2(15) DEFAULT 'active' NOT NULL
        CHECK (status IN ('active', 'achieved', 'cancelled', 'failed')),
    achieved_at       DATE,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_goals_user_status ON goals(user_id, status);

-- GOAL_CONTRIBUTIONS ------------------------------------------
CREATE TABLE goal_contributions (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id             NUMBER NOT NULL,
    amount              NUMBER(15, 2) NOT NULL CHECK (amount > 0),
    contribution_date   DATE NOT NULL,
    note                VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_goalcontrib_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);
CREATE INDEX idx_goalcontribs_goal ON goal_contributions(goal_id, contribution_date DESC);

-- ADHERENCE_SNAPSHOTS -----------------------------------------
CREATE TABLE adherence_snapshots (
    id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id                  NUMBER NOT NULL,
    check_in_date            DATE NOT NULL,
    adherence_score          NUMBER(5, 2) NOT NULL CHECK (adherence_score BETWEEN 0 AND 200),
    expected_saved           NUMBER(15, 2) NOT NULL,
    actual_saved             NUMBER(15, 2) NOT NULL,
    trend                    VARCHAR2(15)
        CHECK (trend IN ('improving', 'declining', 'flat')),
    top_spending_category    VARCHAR2(20),
    created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_adherence_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE
);
CREATE INDEX idx_adherence_goal_date ON adherence_snapshots(goal_id, check_in_date DESC);

-- MONTHLY_SNAPSHOTS -------------------------------------------
CREATE TABLE monthly_snapshots (
    id                       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  NUMBER NOT NULL,
    month_key                VARCHAR2(7) NOT NULL,
    total_spent              NUMBER(15, 2) DEFAULT 0 NOT NULL,
    total_income             NUMBER(15, 2) DEFAULT 0 NOT NULL,
    total_saved              NUMBER(15, 2) DEFAULT 0 NOT NULL,
    auto_rolled_to_savings   NUMBER(15, 2) DEFAULT 0 NOT NULL,
    essentials_spent         NUMBER(15, 2) DEFAULT 0 NOT NULL,
    transport_spent          NUMBER(15, 2) DEFAULT 0 NOT NULL,
    luxuries_spent           NUMBER(15, 2) DEFAULT 0 NOT NULL,
    shopping_spent           NUMBER(15, 2) DEFAULT 0 NOT NULL,
    other_spent              NUMBER(15, 2) DEFAULT 0 NOT NULL,
    start_balance            NUMBER(15, 2) NOT NULL,
    end_balance              NUMBER(15, 2) NOT NULL,
    created_at               TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_snapshot_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_snapshot_user_month UNIQUE (user_id, month_key)
);

-- GAMIFICATION_STATE ------------------------------------------
CREATE TABLE gamification_state (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               NUMBER NOT NULL UNIQUE,
    current_streak        NUMBER DEFAULT 0 NOT NULL,
    longest_streak        NUMBER DEFAULT 0 NOT NULL,
    total_days_logged     NUMBER DEFAULT 0 NOT NULL,
    under_budget_days     NUMBER DEFAULT 0 NOT NULL,
    months_completed      NUMBER DEFAULT 0 NOT NULL,
    last_log_date         DATE,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_gamification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- PENALTY_STATE -----------------------------------------------
CREATE TABLE penalty_state (
    id                         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                    NUMBER NOT NULL UNIQUE,
    strike_count               NUMBER(1) DEFAULT 0 NOT NULL
        CHECK (strike_count BETWEEN 0 AND 3),
    last_check_in_result       VARCHAR2(10)
        CHECK (last_check_in_result IN ('pass', 'fail')),
    chatbot_locked_until       TIMESTAMP,
    quickadd_locked_until      TIMESTAMP,
    penalty_screen_required    NUMBER(1) DEFAULT 0 NOT NULL,
    exceptions_used_this_year  NUMBER DEFAULT 0 NOT NULL,
    intensity                  VARCHAR2(10) DEFAULT 'standard' NOT NULL
        CHECK (intensity IN ('off', 'soft', 'standard', 'hard')),
    allow_chatbot_lock         NUMBER(1) DEFAULT 1 NOT NULL,
    allow_quickadd_lock        NUMBER(1) DEFAULT 1 NOT NULL,
    updated_at                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_penalty_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ACHIEVEMENTS ------------------------------------------------
CREATE TABLE achievements (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            NUMBER NOT NULL,
    achievement_key    VARCHAR2(50) NOT NULL,
    unlocked_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_achievement_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_achievement_user_key UNIQUE (user_id, achievement_key)
);

-- CHAT_MESSAGES -----------------------------------------------
CREATE TABLE chat_messages (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    role          VARCHAR2(10) NOT NULL CHECK (role IN ('user', 'assistant')),
    content       CLOB NOT NULL,
    language      VARCHAR2(2) CHECK (language IN ('ar', 'en')),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_chat_user_date ON chat_messages(user_id, created_at DESC);
